projects:
  3card:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/amplify/**/*
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql/amplify
        maxDepth: 2
extensions:
  amplify:
    version: 3
